import { useState } from "react";
import { TrendingUp, Shield, UtensilsCrossed, FileSearch, Sparkles, ArrowRight, Check, X } from "lucide-react";
import { motion } from "framer-motion";

interface Props {
  sipAmount: number;
  emergencyFund: number;
  savings: number;
  customActions?: { label: string; sub: string; done: boolean }[];
}

const ActionPlan = ({ sipAmount, emergencyFund, savings, customActions }: Props) => {
  const defaultActions = [
    { icon: TrendingUp, label: `Invest ₹${sipAmount.toLocaleString("en-IN")} in SIP`, sub: "Recommended: Index Funds / Axis Growth", tag: "Investment" },
    { icon: Shield, label: `Save ₹${emergencyFund.toLocaleString("en-IN")} to emergency fund`, sub: "Liquid Savings Account", tag: "Savings" },
    { icon: UtensilsCrossed, label: "Reduce food delivery spend by ₹2,000", sub: "Target: ₹4,500 total monthly limit", tag: "Spending" },
    { icon: FileSearch, label: "Review insurance coverage", sub: "Review term policy before 10th", tag: "Protection" },
  ];

  const actions = customActions 
    ? customActions.map(a => ({
        icon: a.label.toLowerCase().includes("invest") || a.label.toLowerCase().includes("sip") ? TrendingUp : 
              a.label.toLowerCase().includes("save") || a.label.toLowerCase().includes("buffer") ? Shield : Sparkles,
        label: a.label,
        sub: a.sub,
        tag: "Plan"
      }))
    : defaultActions;


  const [checked, setChecked] = useState<number[]>([]);
  const toggle = (i: number) => setChecked((prev) => prev.includes(i) ? prev.filter((x) => x !== i) : [...prev, i]);

  const yearlyBefore = 24000;
  const yearlyAfter = savings * 12;

  return (
    <div className="grid grid-cols-1 lg:grid-cols-5 gap-6">
      {/* Action Plan - Left */}
      <div className="lg:col-span-3 card-et">
        <div className="flex items-center justify-between mb-5">
          <h2 className="font-heading text-lg font-bold text-foreground">This Month's Action Plan</h2>
          <span className="text-[10px] font-body font-medium text-primary bg-primary/10 px-2 py-0.5 rounded-full flex items-center gap-1">
            <Sparkles size={10} /> AUTO-GENERATED BY AI
          </span>
        </div>

        <motion.div 
          initial="hidden"
          animate="visible"
          variants={{
            hidden: { opacity: 0 },
            visible: { opacity: 1, transition: { staggerChildren: 0.1 } }
          }}
          className="space-y-3"
        >
          {actions.map((action, i) => {
            const done = checked.includes(i);
            const Icon = action.icon;
            return (
              <motion.button 
                variants={{
                  hidden: { opacity: 0, x: -20 },
                  visible: { opacity: 1, x: 0 }
                }}
                whileHover={{ scale: 1.01 }}
                whileTap={{ scale: 0.98 }}
                key={i} 
                onClick={() => toggle(i)} 
                className={`w-full flex items-center gap-4 p-4 rounded-xl border transition-all duration-300 text-left relative overflow-hidden group ${
                done ? "bg-success/5 border-success/20 opacity-70" : "bg-card border-border hover:border-primary/40 hover:shadow-md hover:bg-secondary/20"
              }`}>
                {/* Subtle highlight on hover */}
                {!done && <div className="absolute inset-0 bg-gradient-to-r from-primary/0 via-primary/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 pointer-events-none" />}
                
                <div className={`w-6 h-6 rounded-full border-2 flex items-center justify-center transition-all duration-300 shrink-0 relative z-10 ${
                  done ? "bg-success border-success scale-110" : "border-border/60 group-hover:border-primary/50"
                }`}>
                  {done && <motion.svg initial={{ scale: 0 }} animate={{ scale: 1 }} width="12" height="12" viewBox="0 0 12 12" fill="none"><path d="M2.5 6L5 8.5L9.5 3.5" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" className="text-white" /></motion.svg>}
                </div>
                <div className={`w-10 h-10 rounded-xl flex items-center justify-center shrink-0 transition-colors duration-300 relative z-10 ${
                  done ? "bg-success/10" : "bg-primary/10 group-hover:bg-primary/15"
                }`}>
                  <Icon size={18} className={done ? "text-success" : "text-primary"} />
                </div>
                <div className="flex-1 min-w-0 relative z-10">
                  <p className={`text-[15px] font-body font-semibold transition-colors duration-300 ${done ? "line-through text-muted-foreground" : "text-foreground group-hover:text-primary"}`}>{action.label}</p>
                  <p className="text-xs font-body text-muted-foreground mt-0.5">{action.sub}</p>
                </div>
              </motion.button>
            );
          })}
        </motion.div>
      </div>

      {/* Projected Impact - Right */}
      <div className="lg:col-span-2 card-et flex flex-col">
        <h2 className="font-heading text-lg font-bold text-foreground mb-5">Projected Impact</h2>

        {/* Before vs After mini */}
        <div className="grid grid-cols-2 gap-3 mb-5">
          <div className="p-3 bg-secondary/50 rounded-lg text-center">
            <p className="text-[10px] font-body text-muted-foreground uppercase tracking-wider flex items-center justify-center gap-1 mb-1">
              <X size={10} /> Without AI Mentor
            </p>
            <p className="text-lg font-heading font-bold text-muted-foreground">₹2,000</p>
            <p className="text-[10px] font-body text-muted-foreground">Avg. Monthly Savings</p>
          </div>
          <div className="p-3 bg-primary/[0.05] border border-primary/15 rounded-lg text-center">
            <p className="text-[10px] font-body text-primary uppercase tracking-wider flex items-center justify-center gap-1 mb-1 font-medium">
              <Check size={10} /> With AI Mentor
            </p>
            <p className="text-lg font-heading font-bold text-gradient-red">₹{savings.toLocaleString("en-IN")}</p>
            <p className="text-[10px] font-body text-muted-foreground">Projected Monthly Savings</p>
          </div>
        </div>

        {/* Yearly progress */}
        <div className="mt-auto p-5 bg-gradient-to-br from-secondary/40 to-secondary/10 rounded-xl border border-border/60 shadow-inner relative overflow-hidden group">
          <div className="absolute right-0 top-0 opacity-5 group-hover:opacity-10 transition-opacity duration-300 scale-150 translate-x-1/4 -translate-y-1/4 pointer-events-none">
            <TrendingUp size={120} />
          </div>
          <p className="text-xs font-body text-muted-foreground uppercase tracking-wider mb-3 font-semibold relative z-10">Calculated Yearly Progress</p>
          <div className="flex items-center gap-4 relative z-10">
            <span className="text-lg font-heading font-bold text-muted-foreground">₹{yearlyBefore.toLocaleString("en-IN")}</span>
            <div className="flex-1 h-px bg-border relative">
              <ArrowRight size={14} className="text-primary absolute right-0 top-1/2 -translate-y-1/2 bg-secondary/40 px-1 box-content" />
            </div>
            <span className="text-2xl font-heading font-bold text-gradient-red drop-shadow-sm">₹{yearlyAfter.toLocaleString("en-IN")}</span>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ActionPlan;
